### ISSUE TITLE
How to install AEM/Oracle Java via yum

### ISSUE THREAD

**Issue by sebastianwr** [pmarkham/ansible-adobe-aem#2]
Hi,

I noticed that the _adobecq_ and _java_ role install AEM and Oracle Java via yum. Can you explain how you do this? Do you have to build a custom RPM for it?

Kind regards,
Sebastian

**Comment by pmarkham** [comment]
I believe Java is already provided as an RPM.

We did create a custom RPM for Adobecq.

**Comment by sebastianwr** [comment]
Thanks for the feedback. That is right, java is provided as an rpm by Oracle, so can be installed as an external rpm (not from a repository, though). 

Can you tell me where you store the rpm so that it is accessible for installation via ansible/yum?

**Comment by pmarkham** [comment]
We put both the Java RPM and the Adobe RPM into our own Yum repository. This is easy to create:
- Copy the RPM files to a directory on a web server
- Run 'createrepo'
- Create a file in /etc/yum.repos.d on the systems that need to use the packages (using Ansible!). This points to the URL of the webserver with the repository. 
- Do a 'yum install' of the packages -- it'll automatically search all repositories listed in /etc/yum.repos.d

**Comment by sebastianwr** [comment]
Great, thank you so much :)

**Comment by sebastianwr** [comment]
One more question: I saw that you explicitely state the jdk version in the package name. However I now have downloaded 2 rpms from Oracle (for Java 7 and 8) and put them in the repository and ran `createrepo`

When I do `yum list available jdk*` I get:
- jdk (Version: 1.7.0-79)
- jdk1.8.0-65 (Version: 1.8.0-65)

Have you encountered this and happen to know why this is the case and if I can make the version explicit in both of the package names?

**Comment by pmarkham** [comment]
You can multiple versions in the repo; this isn't a problem. You should be able to just add the version string onto the end of the package name when you install it, e.g. `yum install jdk-1.7.0-79`

**Comment by sebastianwr** [comment]
True, did not know that. Thanks.
And thank you very much for making this project public, great job and helps us a lot!
